### ISSUE TITLE
LCM: make it compatible with latest k8s 1.21 and vault latest stable version

### ISSUE THREAD

**Issue by commjoen** [commjoen/wrongsecrets#109]
LCM: make it compatible with latest k8s 1.21 and vault latest stable version

**Comment by tiborhercz** [comment]
I will be picking this issue up. I expect to finish it in the upcoming 4 weeks.

**Comment by tiborhercz** [comment]
@commjoen Could you move this issue on the Kanban board to 'in progress'?

**Comment by commjoen** [comment]
Thank you @tiborhercz ! That's awesome news! Hope to have by then completed #150 so we can integrate your suggested changes soon ^^. This is awesome!

**Comment by commjoen** [comment]
> 

done! welcome to the team (again ^^)

**Comment by commjoen** [comment]
> @commjoen Could you move this issue on the Kanban board to 'in progress'?

Done!

**Comment by commjoen** [comment]
Fixed in #208  thank you @tiborhercz !!!
