### ISSUE TITLE
Add solution to hint challenge 12

### ISSUE THREAD

**Issue by davevs** [commjoen/wrongsecrets#142]
'docker history' is providing a better way to solve challenge 12 then the mentioned 'docker inspect'

**Comment by davevs** [comment]
Description of challenge still mentions docker inspect instead of docker history

**Comment by commjoen** [comment]
![image](https://user-images.githubusercontent.com/1457214/148728306-906c67bd-406d-4fd6-a5a8-646609c7822f.jpeg)

**Comment by commjoen** [comment]
@davevs i guess it is now docker history instead of inspect with https://github.com/commjoen/wrongsecrets/commit/b5ceab3a62af8748f82212f3a306cb6e43ce744c .Can we close it?

**Comment by davevs** [comment]
LGTM!
