### ISSUE TITLE
Project version in pom.xml should be updated during release

### ISSUE THREAD

**Issue by MarcinNowak-codes** [commjoen/wrongsecrets#161]
In the `pom.xml` file artifact version:
```
<version>0.0.2-SNAPSHOT</version>
```
when docker container is starting in the logs is:
```
Starting WrongSecretsApplication v0.0.2-SNAPSHOT using Java 17
```
it can be confusing.

During release or merge PR into `master` branch version number should be increased automatically. It can be implemented with 
`org.apache.maven.plugins:maven-release-plugin`. Job in CI/CD's pipeline requires privilege to push directly into `master`. This is one more place for `Wrong Secrets` e.g.

```
./mvnw clean org.apache.maven.plugins:maven-release-plugin:2.5.3:prepare org.apache.maven.plugins:maven-release-plugin:2.5.3:perform -DautoVersionSubmodules -Darguments="-DskipTests -DskipITs -Dusername="username" -Dpassword="password"
```

Moreover, in `Dockerfile` version is hardcoded:
```
COPY --chown=wrongsecrets target/wrongsecrets-0.0.2-SNAPSHOT.jar /application.jar
```
and it has to be taken into account.

**Comment by commjoen** [comment]
Good point! Let's have a look at automating this in a better way so that namings are similar.

**Comment by commjoen** [comment]
Possible solution: use https://maven.apache.org/maven-release/maven-release-plugin/examples/update-versions.html and a parameter in the Dockerfile to clean this up :-)

**Comment by RubenAtBinx** [comment]
I'll can give it a try

**Comment by commjoen** [comment]
Thank you soo much ! Looking forward to it :).
