### ISSUE TITLE
Update challenge 1

### ISSUE THREAD

**Issue by commjoen** [commjoen/wrongsecrets#255]
Thanks to @tghosth: we found out that
- trufflehog has too many versions with deteciton rules. so the trufflehog version / way of working needs to be explicit (E.g. th3 / docker does not work)
- it might be good to just add instrution to let people grep for the password
- it is a good idea to add git-secrets as a detection method: with either `git secrets --add 'password\s*=\s*.+'` or `git secrets --scan`

**Comment by tghosth** [comment]
Note that there are spoilers here. 

you need to execute both commands, (note I have refined the second one :) ):

```git secrets --add 'password\s*=\s*.+'```
```git secrets --scan 2> >(grep ".java")```

This can also be used for challenge 2 with 

```git secrets --add 'password\s*=\s*.+'```
```git secrets --scan 2> >(grep "application.properties")```

**Comment by RemakingEden** [comment]
I'm going to try and take a look at this if thats okay?

**Comment by commjoen** [comment]
Hi @RemakingEden , that is more than ok! You are very very welcome!
