### ISSUE TITLE
Build Docker image for feature branch

### ISSUE THREAD

**Issue by MarcinNowak-codes** [commjoen/wrongsecrets#266]
As a developer and tester I want to have possibility to test Docker image build for feature branch to check correctness of whole application before merge.

**Motivation:**
Some secrets are generated by script `.github/scripts/docker-create-and-push.sh` and stored inside Docker's image. Running this scrip on local machine is difficult without commenting some command e.g. `git push --tags`.

Related to #264

**Comment by commjoen** [comment]
Good point! Maybe we can break that down in 2 steps? 
- [ ] have a local script to do this
- [ ] have a github action to do this

**Comment by RemakingEden** [comment]
I'm going to take a look at this if thats okay?

**Comment by RemakingEden** [comment]
@commjoen Could you explain what the current release flow is please? Without a develop branch im a little confused.

Would it make sense that when people make changes they merge there feature branch into develop and then when develop is merged into master it creates and pushes a new container?

**Comment by commjoen** [comment]
Notes of the call between @commjoen and @RemakingEden 👍 
1. make sure we use one single script 
2. move anything regarding the actual pushing of the image and tagging of the image behind an argument
3. create a Github action which creates the container, spins it up, and does curls to:
- localhost:8080/spoil-4
- localhost:8080/spoil-17

**Comment by RemakingEden** [comment]
> Notes of the call between @commjoen and @RemakingEden 👍
> 
> * [ ]   make sure we use one single script
> * [ ]  no arguments: just build a container for no-vault
> * [ ]  spring-profile argument: build the given spring profile
> * [ ]  help argument: display help only
> * [ ]  publish argument: do the same as the current  script does (in .github/scripts/docker-create-and-push.sh) (so no spring profile, but do all of them)
> * [ ]  test argument: after the container is build and spin up (using no-vault spring profile!), run a few curls to see if the container responds (only usable as a single Arg!) (just run the single arg)
> * [ ]  run the script with test argument in Github Action: just use the new script and call it as an argument ot hte script executioner
> 
> Script lay-out:
> 
> * secrets generation function
> * help function
> * container build function
> * container push function
> * container container test function
> * shell + OS test function: WARN WHEN NOT UBUNTU/MACOS-X/Fedora
> * installed materials function (see existing ones are SEd/etc. installed?)
> * working dir function: check pwd : are we in .github/scripts? if not? GO THERE!
> * git related (restore secret files/commit pom&changes/do the git tagging) function
> * go over arguments and call functions required in the same order as the main script already does, but now us
