### ISSUE TITLE
Challenge 4, slightly confusing answer

### ISSUE THREAD

**Issue by RemakingEden** [commjoen/wrongsecrets#288]
Hi,

Ive just completed challenge 4 and I found the answer a little confusing. I just wanted to see if anyone else had the same issue and it would be worth changing. I'm happy to do the work if people agree. As my issue will include the answer i'll put the rest in a summary tag.

<details>
  <summary>Spolier - No cheating!</summary>
  
The answer to challenge 4 is 'This is just a temporary new version of the password' and can be found here.

```bash
"ARG_BASED_PASSWORD='This is just a temporary new version of the password'",
```

I tried for a long time to input 

```
This is just a temporary new version of the password
```

without the apostrophes as I just presumed they were there to make it into a string in the code.

So I guess I have a couple questions?
- Has anyone else had this issue?
- Are the apostrophes required? Or would it work without them like the env based variables?

If they arent required I wonder if they should be removed as it is an extra confusion that may make user stop completing the challenges with no extra gain.

Anyway, please let me know if im just the idiot. No problem if thats the case. I'll be happy to close.
  
</details>

**Comment by commjoen** [comment]
Thank you for reporting the issue!  This looks like something that could use improvement indeed! Let me get back to you next week on this.

**Comment by commjoen** [comment]
Fixed in https://github.com/commjoen/wrongsecrets/pull/289. Thanks!
