### ISSUE TITLE
Add GCP challenges

### ISSUE THREAD

**Issue by benno001** [commjoen/wrongsecrets#40]
- [x] Create challenge with secret in state
- [x] Create challenge with pod exec
- [x] disable links of certain challenge is not possible
- [x] Update javacode to recognize environment and switch explanation
- [x] Add explanations for GCP
- [x] Have consistent AWS/GCP naming for challenge-explanations
- [x] Create challenge 11 in GCP (Create challenge with overprivileged service account)

**Comment by bendehaan** [comment]
Addressed in #87
