### ISSUE TITLE
Have CTFD/FacebookCTF support

### ISSUE THREAD

**Issue by commjoen** [commjoen/wrongsecrets#94]
We would like to have a simple script that generates the required files to be loaded up with CTFD to use WrongSecrets in a CTF

- [x] Have a Heroku test env (wrongsecrets-ctf.herokuapp.com)
- [x] Have basic CTFD support
- [x] Optimise generation of challenges api response
- [x] Add tests for hmacing 
- [x] Make sure we can disable spoiling ;-)
- [x] Ensure hints are working
- [x] Improve categorization - https://github.com/commjoen/wrongsecrets/issues/325 
- [x] implement weighted scoring for non-ctf mode
- [x] ~Standardise naming in properties and dockerfiles (consistent capital usage)~
- [x] improve docs on how to set it up.
- [x] Make FacebookCTF work based on same tooling
- [x] See if we need our own generator script or work fully with https://github.com/juice-shop/juice-shop-ctf and make it recent ctfd compatible

**Comment by RemakingEden** [comment]
I'd be interested in testing this. I'm considering running a mini CTF at my work. Is the work complete?

**Comment by commjoen** [comment]
Yes sir! We can do a prerun together during a call and then you can run the ctf for sure :-)
